#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Networking/ExpressRoute.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.network/expressroutecircuits'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $data = $1.PROPERTIES
                $sku = $1.SKU
                $Retired = $Retirements | Where-Object { $_.id -eq $1.id }
                if ($Retired)
                    {
                        $RetiredFeature = foreach ($Retire in $Retired)
                            {
                                $RetiredServiceID = $Unsupported | Where-Object {$_.Id -eq $Retired.ServiceID}
                                $tmp0 = [pscustomobject]@{
                                        'RetiredFeature'            = $RetiredServiceID.RetiringFeature
                                        'RetiredDate'               = $RetiredServiceID.RetirementDate
                                    }
                                $tmp0
                            }
                        $RetiringFeature = if (@($RetiredFeature.RetiredFeature).count -gt 1) { $RetiredFeature.RetiredFeature | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredFeature}
                        $RetiringFeature = [string]$RetiringFeature
                        $RetiringFeature = if ($RetiringFeature -like '* ,*') { $RetiringFeature -replace ".$" }else { $RetiringFeature }

                        $RetiringDate = if (@($RetiredFeature.RetiredDate).count -gt 1) { $RetiredFeature.RetiredDate | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredDate}
                        $RetiringDate = [string]$RetiringDate
                        $RetiringDate = if ($RetiringDate -like '* ,*') { $RetiringDate -replace ".$" }else { $RetiringDate }
                    }
                else
                    {
                        $RetiringFeature = $null
                        $RetiringDate = $null
                    }
                $Auths = if(![string]::IsNullOrEmpty($data.authorizations)){$data.authorizations}else{'0'}
                $Tags = if(![string]::IsNullOrEmpty($1.tags.psobject.properties)){$1.tags.psobject.properties}else{'0'}
'@

    AdditionalRowLoops = @(
        @{
            Variable = 'Auth'
            # AB#6845 decision ($Auth): NO EmitNullWhenEmpty, deliberately. $Auths falls back to
            # '0' when the circuit carries no authorizations, so the circuit keeps its row.
            #
            # A circuit with no authorizations is the normal state for one not yet linked to a
            # VNet gateway -- it is ordered, billing, and connected to nothing, which is a finding
            # rather than a reason to omit it. The sentinel already guarantees the row; the flag
            # would never fire.
            Source = '$Auths'
            Preamble = ''
        }
    )

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '(Get-AZSCSafeProperty -InputObject $sub1 -Path ''name'')'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Retiring Feature'
            Expression = '$RetiringFeature'
        }
        @{
            Name = 'Retiring Date'
            Expression = '$RetiringDate'
        }
        @{
            Name = 'SKU'
            Expression = '$sku.tier'
        }
        @{
            Name = 'Billing Model'
            Expression = '$sku.family'
        }
        @{
            Name = 'Authorization'
            Expression = '(Get-AZSCSafeProperty -InputObject $Auth -Path ''Name'')'
        }
        @{
            Name = 'Circuit Status'
            Expression = '$data.circuitProvisioningState'
        }
        @{
            Name = 'Provider Status'
            Expression = '$data.serviceProviderProvisioningState'
        }
        @{
            Name = 'Provider'
            Expression = '$data.serviceProviderProperties.serviceProviderName'
        }
        @{
            Name = 'Bandwidth'
            Expression = '$data.serviceProviderProperties.bandwidthInMbps'
        }
        @{
            Name = 'Peering Location'
            Expression = '$data.serviceProviderProperties.peeringLocation'
        }
        @{
            Name = 'GlobalReach Enabled'
            Expression = '$data.globalReachEnabled'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Express Route'
        TableNamePrefix = 'ERs_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Name'
            'Location'
            'Retiring Feature'
            'Retiring Date'
            'Provider Status'
            'Provider'
            'Peering Location'
            'Bandwidth'
            'SKU'
            'Billing Model'
            'Authorization'
            'Circuit Status'
            'GlobalReach Enabled'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = 'Resource U'
        NumberFormat = '0'
        ConditionalText = @(
            'New-ConditionalText -Range E2:E100 -ConditionalType ContainsText'
        )
    }

    SourceCollector = 'Modules/Public/InventoryModules/Networking/ExpressRoute.ps1'
}

