#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/AI/MLPipelines.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/MLPipelines'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ws = $Resources | Where-Object { $_.id -eq $1.PARENTID } | Select-Object -First 1
                        $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
                        $ResUCount = 1
                        $jProp     = $1.properties
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'Workspace Name'
            Expression = '$ws.NAME'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$ws.RESOURCEGROUP'
        }
        @{
            Name = 'Pipeline Name'
            Expression = '$1.name'
        }
        @{
            Name = 'Pipeline ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Display Name'
            Expression = 'if ($jProp.displayName)          { $jProp.displayName }          else { ''N/A'' }'
        }
        @{
            Name = 'Status'
            Expression = 'if ($jProp.status)               { $jProp.status }               else { ''N/A'' }'
        }
        @{
            Name = 'Created Time'
            Expression = 'if ($jProp.creationContext.createdAt) { ([datetime]$jProp.creationContext.createdAt).ToString(''yyyy-MM-dd HH:mm'') } else { ''N/A'' }'
        }
        @{
            Name = 'Last Modified'
            Expression = 'if ($jProp.creationContext.lastModifiedAt) { ([datetime]$jProp.creationContext.lastModifiedAt).ToString(''yyyy-MM-dd HH:mm'') } else { ''N/A'' }'
        }
        @{
            Name = 'Description'
            Expression = 'if ($jProp.description)          { $jProp.description }          else { ''N/A'' }'
        }
        @{
            Name = 'Experiment Name'
            Expression = 'if ($jProp.experimentName)       { $jProp.experimentName }       else { ''N/A'' }'
        }
        @{
            Name = 'Compute ID'
            Expression = 'if ($jProp.settings.defaultCompute) { $jProp.settings.defaultCompute } else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = ''''''
        }
        @{
            Name = 'Tag Value'
            Expression = ''''''
        }
    )

    Export = @{
        WorksheetName = 'ML Pipelines'
        TableNamePrefix = 'MLPipelinesTable_'
        Columns = @(
            'Workspace Name'
            'Subscription'
            'Resource Group'
            'Pipeline Name'
            'Pipeline ID'
            'Display Name'
            'Status'
            'Created Time'
            'Last Modified'
            'Description'
            'Experiment Name'
            'Compute ID'
            'Resource U'
        )
        TagColumns = @()
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/AI/MLPipelines.ps1'
}

