#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/AI/OpenAIDeployments.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/OpenAIDeployments'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$account = $Resources | Where-Object { $_.id -eq $1.PARENTID } | Select-Object -First 1
                        $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
                        $ResUCount = 1
                        $dData = $1.properties
                        $model = $dData.model
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'Account Name'
            Expression = '$account.NAME'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$account.RESOURCEGROUP'
        }
        @{
            Name = 'Location'
            Expression = '$account.LOCATION'
        }
        @{
            Name = 'Deployment Name'
            Expression = '$1.name'
        }
        @{
            Name = 'Model Name'
            Expression = 'if ($model.name)    { $model.name }    else { ''N/A'' }'
        }
        @{
            Name = 'Model Version'
            Expression = 'if ($model.version) { $model.version } else { ''N/A'' }'
        }
        @{
            Name = 'Model Format'
            Expression = 'if ($model.format)  { $model.format }  else { ''N/A'' }'
        }
        @{
            Name = 'Scale Type'
            Expression = 'if ($dData.scaleSettings.scaleType)     { $dData.scaleSettings.scaleType }     else { ''N/A'' }'
        }
        @{
            Name = 'Capacity (PTUs)'
            Expression = 'if ($dData.scaleSettings.capacity)      { $dData.scaleSettings.capacity }      else { ''N/A'' }'
        }
        @{
            Name = 'Dynamic Throttling'
            Expression = 'if ($dData.dynamicThrottlingEnabled -eq $true) { ''Yes'' } else { ''No'' }'
        }
        @{
            Name = 'Provisioning State'
            Expression = 'if ($dData.provisioningState) { $dData.provisioningState } else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = ''''''
        }
        @{
            Name = 'Tag Value'
            Expression = ''''''
        }
    )

    Export = @{
        WorksheetName = 'OpenAI Deployments'
        TableNamePrefix = 'OpenAIDeploymentsTable_'
        Columns = @(
            'Account Name'
            'Subscription'
            'Resource Group'
            'Location'
            'Deployment Name'
            'Model Name'
            'Model Version'
            'Model Format'
            'Scale Type'
            'Capacity (PTUs)'
            'Dynamic Throttling'
            'Provisioning State'
            'Resource U'
        )
        TagColumns = @()
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/AI/OpenAIDeployments.ps1'
}

