#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/AI/SearchIndexes.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/SearchIndexes'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$svc = $Resources | Where-Object { $_.id -eq $1.PARENTID } | Select-Object -First 1
                        $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
                        $ResUCount = 1
                        $fieldsCount   = if ($1.fields)         { @($1.fields).Count }         else { 0 }
                        $analyzers     = if ($1.analyzers)      { @($1.analyzers).Count }      else { 0 }
                        $scoringProfs  = if ($1.scoringProfiles){ @($1.scoringProfiles).Count } else { 0 }
                        $suggesters    = if ($1.suggesters)     { @($1.suggesters).Count }      else { 0 }
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'Service Name'
            Expression = '$svc.NAME'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$svc.RESOURCEGROUP'
        }
        @{
            Name = 'Index Name'
            Expression = '$1.name'
        }
        @{
            Name = 'Fields Count'
            Expression = '$fieldsCount'
        }
        @{
            Name = 'Analyzers Count'
            Expression = '$analyzers'
        }
        @{
            Name = 'Scoring Profiles'
            Expression = '$scoringProfs'
        }
        @{
            Name = 'Suggesters Count'
            Expression = '$suggesters'
        }
        @{
            Name = 'CORS Allowed Origins'
            Expression = 'if ($1.corsOptions.allowedOrigins) { $1.corsOptions.allowedOrigins -join ''; '' } else { ''N/A'' }'
        }
        @{
            Name = 'Default Scoring Profile'
            Expression = 'if ($1.defaultScoringProfile)  { $1.defaultScoringProfile }  else { ''None'' }'
        }
        @{
            Name = 'ETag'
            Expression = 'if ($1.''@odata.etag'')             { $1.''@odata.etag'' }          else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = ''''''
        }
        @{
            Name = 'Tag Value'
            Expression = ''''''
        }
    )

    Export = @{
        WorksheetName = 'Search Indexes'
        TableNamePrefix = 'SearchIndexesTable_'
        Columns = @(
            'Service Name'
            'Subscription'
            'Resource Group'
            'Index Name'
            'Fields Count'
            'Analyzers Count'
            'Scoring Profiles'
            'Suggesters Count'
            'CORS Allowed Origins'
            'Default Scoring Profile'
            'Resource U'
        )
        TagColumns = @()
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/AI/SearchIndexes.ps1'
}

