#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Monitor/SmartDetectorAlertRules.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.alertsmanagement/smartdetectoralertrules'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
            $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
            $data = $1.PROPERTIES
            $Tags = if (![string]::IsNullOrEmpty($1.tags.psobject.properties)) { $1.tags.psobject.properties } else { '0' }

            # Detector info
            $detectorId   = if ($data.detector) { $data.detector.id } else { 'N/A' }
            $detectorName = if ($data.detector) { $data.detector.name } else { 'N/A' }

            # Scope (target Application Insights / resource)
            $scopeResourceId = if ($data.scope) { $data.scope -join '; ' } else { 'N/A' }

            # Action groups
            $actionGroupStr = 'None'
            if ($data.actionGroups -and $data.actionGroups.groupIds) {
                $actionGroupStr = ($data.actionGroups.groupIds | ForEach-Object { ($_ -split '/')[-1] }) -join '; '
            }
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Alert Rule Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'State'
            Expression = 'if ($data.state) { $data.state } else { ''N/A'' }'
        }
        @{
            Name = 'Severity'
            Expression = 'if ($data.severity) { $data.severity } else { ''N/A'' }'
        }
        @{
            Name = 'Frequency'
            Expression = 'if ($data.frequency) { $data.frequency } else { ''N/A'' }'
        }
        @{
            Name = 'Detector ID'
            Expression = '$detectorId'
        }
        @{
            Name = 'Detector Name'
            Expression = '$detectorName'
        }
        @{
            Name = 'Target Scope'
            Expression = '$scopeResourceId'
        }
        @{
            Name = 'Action Groups'
            Expression = '$actionGroupStr'
        }
        @{
            Name = 'Throttling Duration'
            Expression = 'if ($data.throttlingDuration) { $data.throttlingDuration } else { ''PT0M'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Smart Detector Alerts'
        TableNamePrefix = 'SmartAlertTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Alert Rule Name'
            'Location'
            'State'
            'Severity'
            'Frequency'
            'Detector ID'
            'Detector Name'
            'Target Scope'
            'Action Groups'
            'Throttling Duration'
            'Resource U'
        )
        TagColumns = @()
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/Monitor/SmartDetectorAlertRules.ps1'
}

