#
# GENERATED by scripts/Build-ScoutServiceCollector.ps1 from manifests/specs/service-collectors.psd1 (AB#6741).
# Authored as data -- there is no source collector script to drift from. Edit the spec and
# regenerate; do not hand-patch this file.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/ReservationUtilization'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $data = $1.PROPERTIES
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $SubName = $sub1.Name
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.PARENTID'
        }
        @{
            Name = 'Subscription'
            Expression = '$SubName'
        }
        @{
            Name = 'Reservation'
            Expression = '$1.PARENTNAME'
        }
        @{
            Name = 'SKU'
            Expression = '$data.skuName'
        }
        @{
            Name = 'Usage Date'
            Expression = '[string]$data.usageDate'
        }
        @{
            Name = 'Reserved Hours'
            Expression = '[string]$data.reservedHours'
        }
        @{
            Name = 'Used Hours'
            Expression = '[string]$data.usedHours'
        }
        @{
            Name = 'Avg Utilization %'
            Expression = '[string]$data.avgUtilizationPercentage'
        }
        @{
            Name = 'Min Utilization %'
            Expression = '[string]$data.minUtilizationPercentage'
        }
        @{
            Name = 'Max Utilization %'
            Expression = '[string]$data.maxUtilizationPercentage'
        }
        @{
            Name = 'Purchased Quantity'
            Expression = '[string]$data.purchasedQuantity'
        }
        @{
            Name = 'Remaining Quantity'
            Expression = '[string]$data.remainingQuantity'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
    )

    Export = @{
        WorksheetName = 'Reservation Utilization'
        TableNamePrefix = 'ReservationUtilizationTable_'
        Columns = @(
            'Subscription'
            'Reservation'
            'SKU'
            'Usage Date'
            'Reserved Hours'
            'Used Hours'
            'Avg Utilization %'
            'Min Utilization %'
            'Max Utilization %'
            'Purchased Quantity'
            'Remaining Quantity'
            'Resource U'
        )
        TagColumns = @()
        NumberFormat = '0'
        ConditionalText = @()
    }
}
