#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Analytics/DataExplorerCluster.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.kusto/clusters'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
                $data = $1.PROPERTIES
                $sku = $1.SKU
                $Retired = $Retirements | Where-Object { $_.id -eq $1.id }
                if ($Retired) 
                    {
                        $RetiredFeature = foreach ($Retire in $Retired)
                            {
                                $RetiredServiceID = $Unsupported | Where-Object {$_.Id -eq $Retired.ServiceID}
                                $tmp0 = [pscustomobject]@{
                                        'RetiredFeature'            = $RetiredServiceID.RetiringFeature
                                        'RetiredDate'               = $RetiredServiceID.RetirementDate 
                                    }
                                $tmp0
                            }
                        $RetiringFeature = if (@($RetiredFeature.RetiredFeature).count -gt 1) { $RetiredFeature.RetiredFeature | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredFeature}
                        $RetiringFeature = [string]$RetiringFeature
                        $RetiringFeature = if ($RetiringFeature -like '* ,*') { $RetiringFeature -replace ".$" }else { $RetiringFeature }

                        $RetiringDate = if (@($RetiredFeature.RetiredDate).count -gt 1) { $RetiredFeature.RetiredDate | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredDate}
                        $RetiringDate = [string]$RetiringDate
                        $RetiringDate = if ($RetiringDate -like '* ,*') { $RetiringDate -replace ".$" }else { $RetiringDate }
                    }
                else 
                    {
                        $RetiringFeature = $null
                        $RetiringDate = $null
                    }
                $VNET = if(![string]::IsNullOrEmpty($data.virtualNetworkConfiguration.subnetid)){(Get-AZSCIdSegment -Id $data.virtualNetworkConfiguration.subnetid -Index 8)}else{$null}
                $Subnet = if(![string]::IsNullOrEmpty($data.virtualNetworkConfiguration.subnetid)){(Get-AZSCIdSegment -Id $data.virtualNetworkConfiguration.subnetid -Index 10)}else{$null}
                $DataPIP = if(![string]::IsNullOrEmpty($data.virtualNetworkConfiguration.dataManagementPublicIpId)){(Get-AZSCIdSegment -Id $data.virtualNetworkConfiguration.dataManagementPublicIpId -Index 8)}else{$null}
                $EnginePIP = if(![string]::IsNullOrEmpty($data.virtualNetworkConfiguration.enginePublicIpId)){(Get-AZSCIdSegment -Id $data.virtualNetworkConfiguration.enginePublicIpId -Index 8)}else{$null}
                $TenantPerm = if($data.trustedExternalTenants.value -eq '*'){'All Tenants'}else{$data.trustedExternalTenants.value}
                $AutoScale = if($data.optimizedAutoscale.isEnabled -eq 'true'){'Enabled'}else{'Disabled'}
                $Tags = if(![string]::IsNullOrEmpty($1.tags.psobject.properties)){$1.tags.psobject.properties}else{'0'}
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Retiring Feature'
            Expression = '$RetiringFeature'
        }
        @{
            Name = 'Retiring Date'
            Expression = '$RetiringDate'
        }
        @{
            Name = 'Compute specifications'
            Expression = '$sku.name'
        }
        @{
            Name = 'Instance count'
            Expression = '$sku.capacity'
        }
        @{
            Name = 'State'
            Expression = '$data.state'
        }
        @{
            Name = 'State Reason'
            Expression = '$data.stateReason'
        }
        @{
            Name = 'Virtual Network'
            Expression = '$VNET'
        }
        @{
            Name = 'Subnet'
            Expression = '$Subnet'
        }
        @{
            Name = 'Data Management Public IP'
            Expression = '$DataPIP'
        }
        @{
            Name = 'Engine Public IP'
            Expression = '$EnginePIP'
        }
        @{
            Name = 'Tenants Permissions'
            Expression = '$TenantPerm'
        }
        @{
            Name = 'Disk Encryption'
            Expression = '$data.enableDiskEncryption'
        }
        @{
            Name = 'Streaming Ingestion'
            Expression = '$data.enableStreamingIngest'
        }
        @{
            Name = 'Optimized Autoscale'
            Expression = '$AutoScale'
        }
        @{
            Name = 'Optimized Autoscale Min'
            Expression = '$data.optimizedAutoscale.minimum'
        }
        @{
            Name = 'Optimized Autoscale Max'
            Expression = '$data.optimizedAutoscale.maximum'
        }
        @{
            Name = 'URI'
            Expression = '$data.uri'
        }
        @{
            Name = 'Data Ingestion Uri'
            Expression = '$data.dataIngestionUri'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Data Explorer Clusters'
        TableNamePrefix = 'DTExplTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Name'
            'Location'
            'Retiring Feature'
            'Retiring Date'
            'Compute specifications'
            'Instance count'
            'State'
            'State Reason'
            'Virtual Network'
            'Subnet'
            'Data Management Public IP'
            'Engine Public IP'
            'Tenants Permissions'
            'Disk Encryption'
            'Streaming Ingestion'
            'Optimized Autoscale'
            'Optimized Autoscale Min'
            'Optimized Autoscale Max'
            'URI'
            'Data Ingestion Uri'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = 'Resource U'
        NumberFormat = '0'
        ConditionalText = @(
            'New-ConditionalText ''All Tenants'' -Range O:O'
            'New-ConditionalText FALSE -Range P:P'
            'New-ConditionalText Disabled -Range R:R'
            'New-ConditionalText -Range E2:E100 -ConditionalType ContainsText'
        )
    }

    SourceCollector = 'Modules/Public/InventoryModules/Analytics/DataExplorerCluster.ps1'
}

