#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Analytics/Streamanalytics.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.streamanalytics/streamingjobs'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    SetupPreamble = @'
$StreamAnalyticsCluster = $Resources | Where-Object { $_.TYPE -eq 'microsoft.streamanalytics/clusters' }
    $StreamAnalyticsJobs = $Resources | Where-Object { $_.TYPE -eq 'microsoft.streamanalytics/streamingjobs' }
'@

    SetupVariables = @(
        'StreamAnalyticsCluster'
        'StreamAnalyticsJobs'
    )

    Preamble = @'
$ResUCount = 1
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $data = $1.PROPERTIES
                $Cluster = ''
                $Cluster = $StreamAnalyticsCluster | Where-Object {$_.id -eq $data.cluster.id}
                $Creadate = if($data.createdDate){[string](get-date $data.createdDate)}else{''}
                $Retired = $Retirements | Where-Object { $_.id -eq $1.id }
                if ($Retired) 
                    {
                        $RetiredFeature = foreach ($Retire in $Retired)
                            {
                                $RetiredServiceID = $Unsupported | Where-Object {$_.Id -eq $Retired.ServiceID}
                                $tmp0 = [pscustomobject]@{
                                        'RetiredFeature'            = $RetiredServiceID.RetiringFeature
                                        'RetiredDate'               = $RetiredServiceID.RetirementDate 
                                    }
                                $tmp0
                            }
                        $RetiringFeature = if (@($RetiredFeature.RetiredFeature).count -gt 1) { $RetiredFeature.RetiredFeature | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredFeature}
                        $RetiringFeature = [string]$RetiringFeature
                        $RetiringFeature = if ($RetiringFeature -like '* ,*') { $RetiringFeature -replace ".$" }else { $RetiringFeature }

                        $RetiringDate = if (@($RetiredFeature.RetiredDate).count -gt 1) { $RetiredFeature.RetiredDate | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredDate}
                        $RetiringDate = [string]$RetiringDate
                        $RetiringDate = if ($RetiringDate -like '* ,*') { $RetiringDate -replace ".$" }else { $RetiringDate }
                    }
                else 
                    {
                        $RetiringFeature = $null
                        $RetiringDate = $null
                    }
                $LastOutput = if($data.lastOutputEventTime){[string](get-date $data.lastOutputEventTime)}else{''}
                $OutputStart = if($data.outputStartTime){[string](get-date $data.outputStartTime)}else{''}
                $ClusterCreatedDate = Get-AZSCSafeProperty -InputObject $Cluster -Path 'properties.createddate'
                $ClusterDate = if($ClusterCreatedDate){[string](get-date($ClusterCreatedDate))}else{''}
                $Tags = if ($null -ne $1.PSObject.Properties['tags'] -and $1.tags -and @($1.tags.PSObject.Properties).Count -gt 0) { $1.tags.PSObject.Properties } else { '0' }

                $ClusterSubscriptionId = Get-AZSCSafeProperty -InputObject $Cluster -Path 'subscriptionid'
                $sub2 = $SUB | Where-Object { $_.id -eq $ClusterSubscriptionId }
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Cluster Subscription'
            Expression = '$sub2.Name'
        }
        @{
            Name = 'Cluster Resource Group'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''resourcegroup'''
        }
        @{
            Name = 'Cluster Name'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''NAME'''
        }
        @{
            Name = 'Cluster Location'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''location'''
        }
        @{
            Name = 'Cluster SKU'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''sku.name'''
        }
        @{
            Name = 'Retiring Feature'
            Expression = '$RetiringFeature'
        }
        @{
            Name = 'Retiring Date'
            Expression = '$RetiringDate'
        }
        @{
            Name = 'Capacity Allocated'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''properties.capacityallocated'''
        }
        @{
            Name = 'Capacity Assigned'
            Expression = 'Get-AZSCSafeProperty -InputObject $Cluster -Path ''properties.capacityassigned'''
        }
        @{
            Name = 'Cluster Creation Date'
            Expression = '$ClusterDate'
        }
        @{
            Name = 'Job Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Job Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Job Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Job Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Job Pricing Plan'
            Expression = '$data.sku.name'
        }
        @{
            Name = 'Compatibility Level'
            Expression = '$data.compatibilityLevel'
        }
        @{
            Name = 'Storage Account'
            Expression = '$data.jobstorageaccount.accountname'
        }
        @{
            Name = 'Storage Account Auth Method'
            Expression = '$data.jobstorageaccount.authenticationmode'
        }
        @{
            Name = 'Content Storage Policy'
            Expression = '$data.contentStoragePolicy'
        }
        @{
            Name = 'Created Date'
            Expression = '$Creadate'
        }
        @{
            Name = 'Data Locale'
            Expression = '$data.dataLocale'
        }
        @{
            Name = 'Late Arrival Max Delay in Seconds'
            Expression = '$data.eventsLateArrivalMaxDelayInSeconds'
        }
        @{
            Name = 'Out of Order Max Delay in Seconds'
            Expression = '$data.eventsOutOfOrderMaxDelayInSeconds'
        }
        @{
            Name = 'Out of Order Policy'
            Expression = '$data.eventsOutOfOrderPolicy'
        }
        @{
            Name = 'Job State'
            Expression = '$data.jobState'
        }
        @{
            Name = 'Job Type'
            Expression = '$data.jobType'
        }
        @{
            Name = 'Last Output Event Time'
            Expression = '$LastOutput'
        }
        @{
            Name = 'Output Start Time'
            Expression = '$OutputStart'
        }
        @{
            Name = 'Output Error Policy'
            Expression = '$data.outputErrorPolicy'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Stream Analytics Jobs'
        TableNamePrefix = 'StreamsATable_'
        Columns = @(
            'Cluster Subscription'
            'Cluster Resource Group'
            'Cluster Name'
            'Cluster Location'
            'Cluster SKU'
            'Retiring Feature'
            'Retiring Date'
            'Capacity Allocated'
            'Capacity Assigned'
            'Cluster Creation Date'
            'Job Subscription'
            'Job Resource Group'
            'Job Name'
            'Job Location'
            'Job Pricing Plan'
            'Job State'
            'Compatibility Level'
            'Storage Account'
            'Storage Account Auth Method'
            'Content Storage Policy'
            'Created Date'
            'Data Locale'
            'Late Arrival Max Delay in Seconds'
            'Out of Order Max Delay in Seconds'
            'Out of Order Policy'
            'Job Type'
            'Last Output Event Time'
            'Output Start Time'
            'Output Error Policy'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = 'Resource U'
        NumberFormat = '0'
        ConditionalText = @(
            'New-ConditionalText -Range E2:E100 -ConditionalType ContainsText'
            'New-ConditionalText failed -Range P:P'
        )
    }

    SourceCollector = 'Modules/Public/InventoryModules/Analytics/Streamanalytics.ps1'
}

