#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Compute/AVD.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.desktopvirtualization/hostpools'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    SetupPreamble = @'
$VM =  $Resources | Where-Object {$_.TYPE -eq 'microsoft.compute/virtualmachines'}
    $AVD = $Resources | Where-Object { $_.TYPE -eq 'microsoft.desktopvirtualization/hostpools' }
    $Hosts = $Resources | Where-Object { $_.TYPE -eq 'microsoft.desktopvirtualization/hostpools/sessionhosts' }
'@

    SetupVariables = @(
        'VM'
        'AVD'
        'Hosts'
    )

    Preamble = @'
$ResUCount = 1
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $data = $1.PROPERTIES

                $sessionhosts = @()
                foreach ($h in $Hosts){
                    $n = $h.ID -split '/sessionhosts/' 
                    if ($n[0] -eq $1.id ) 
                    {
                        $sessionhosts += $h                    
                    }

                }
                $Retired = Foreach ($Retirement in $Retirements)
                    {
                        if ($Retirement.id -eq $1.id) { $Retirement }
                    }
                if ($Retired) 
                    {
                        $RetiredFeature = foreach ($Retire in $Retired)
                            {
                                $RetiredServiceID = $Unsupported | Where-Object {$_.Id -eq $Retired.ServiceID}
                                $tmp0 = [pscustomobject]@{
                                        'RetiredFeature'            = $RetiredServiceID.RetiringFeature
                                        'RetiredDate'               = $RetiredServiceID.RetirementDate 
                                    }
                                $tmp0
                            }
                        $RetiringFeature = if (@($RetiredFeature.RetiredFeature).count -gt 1) { $RetiredFeature.RetiredFeature | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredFeature}
                        $RetiringFeature = [string]$RetiringFeature
                        $RetiringFeature = if ($RetiringFeature -like '* ,*') { $RetiringFeature -replace ".$" }else { $RetiringFeature }

                        $RetiringDate = if (@($RetiredFeature.RetiredDate).count -gt 1) { $RetiredFeature.RetiredDate | ForEach-Object { $_ + ' ,' } }else { $RetiredFeature.RetiredDate}
                        $RetiringDate = [string]$RetiringDate
                        $RetiringDate = if ($RetiringDate -like '* ,*') { $RetiringDate -replace ".$" }else { $RetiringDate }
                    }
                else 
                    {
                        $RetiringFeature = $null
                        $RetiringDate = $null
                    }
                if ($1.ZONES) { $Zones = $1.ZONES }else { $Zones = 'Not Configured' }
                $Tags = if(![string]::IsNullOrEmpty($1.tags.psobject.properties)){$1.tags.psobject.properties}else{'0'}
'@

    AdditionalRowLoops = @(
        @{
            Variable = '2'
            Source = '$sessionhosts'
            Preamble = @'
$domain = $2.name.replace(($2.name.split(".")[0]),'')
                    $vmsessionhosts = $VM | Where-Object { $_.ID -eq $2.properties.resourceId}
'@
        }
    )

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Hostpool Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Retiring Feature'
            Expression = '$RetiringFeature'
        }
        @{
            Name = 'Retiring Date'
            Expression = '$RetiringDate'
        }
        @{
            Name = 'Zone'
            Expression = '$Zones'
        }
        @{
            Name = 'HostPool Type'
            Expression = '$data.hostPoolType'
        }
        @{
            Name = 'LoadBalancer'
            Expression = '$data.loadBalancerType'
        }
        @{
            Name = 'maxSessionLimit'
            Expression = '$data.maxSessionLimit'
        }
        @{
            Name = 'preferred AppGroup'
            Expression = '$data.preferredAppGroupType'
        }
        @{
            Name = 'AVD Agent Version'
            Expression = '$2.properties.agentVersion'
        }
        @{
            Name = 'Last Assigned User'
            Expression = '$2.properties.assignedUser'
        }
        @{
            Name = 'Allow New Session'
            Expression = '$2.properties.allowNewSession'
        }
        @{
            Name = 'Update Status'
            Expression = '$2.properties.updateState'
        }
        @{
            Name = 'Hostname'
            Expression = '$vmsessionhosts.name'
        }
        @{
            Name = 'Domain'
            Expression = '$domain'
        }
        @{
            Name = 'VM Size'
            Expression = '$vmsessionhosts.properties.hardwareProfile.vmsize'
        }
        @{
            Name = 'OS Type'
            Expression = '$vmsessionhosts.properties.storageProfile.osdisk.ostype'
        }
        @{
            Name = 'VM Disk Type'
            Expression = '$vmsessionhosts.properties.storageProfile.osdisk.managedDisk.storageAccountType'
        }
        @{
            Name = 'Sessions'
            Expression = '$2.properties.sessions'
        }
        @{
            Name = 'Host Status'
            Expression = '$2.properties.status'
        }
        @{
            Name = 'OS Version'
            Expression = '$2.properties.osVersion'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'AVD'
        TableNamePrefix = 'AVD_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Hostpool Name'
            'Location'
            'Retiring Feature'
            'Retiring Date'
            'Zone'
            'HostPool Type'
            'LoadBalancer'
            'maxSessionLimit'
            'preferred AppGroup'
            'AVD Agent Version'
            'Last Assigned User'
            'Allow New Session'
            'Update Status'
            'Hostname'
            'Domain'
            'VM Size'
            'OS Type'
            'VM Disk Type'
            'Sessions'
            'Host Status'
            'OS Version'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = 'Resource U'
        NumberFormat = '0'
        ConditionalText = @(
            'New-ConditionalText -Range E2:E100 -ConditionalType ContainsText'
            'New-ConditionalText "Not Configured" -Range G:G'
        )
    }

    SourceCollector = 'Modules/Public/InventoryModules/Compute/AVD.ps1'
}

