#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Compute/AVDWorkspaces.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.desktopvirtualization/workspaces'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
            $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
            $data = $1.PROPERTIES
            $Tags = if (![string]::IsNullOrEmpty($1.tags.psobject.properties)) { $1.tags.psobject.properties } else { '0' }

            $appGroupCount = if ($data.applicationGroupReferences) { @($data.applicationGroupReferences).Count } else { 0 }
            $appGroupNames = if ($data.applicationGroupReferences) {
                (@($data.applicationGroupReferences) | ForEach-Object { ($_ -split '/')[-1] }) -join '; '
            } else { 'None' }

            $peCount = if ($data.privateEndpointConnections) { @($data.privateEndpointConnections).Count } else { 0 }
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Friendly Name'
            Expression = 'if ($data.friendlyName)              { $data.friendlyName }              else { ''N/A'' }'
        }
        @{
            Name = 'Description'
            Expression = 'if ($data.description)               { $data.description }               else { ''N/A'' }'
        }
        @{
            Name = 'Application Groups Count'
            Expression = '$appGroupCount'
        }
        @{
            Name = 'Application Groups'
            Expression = '$appGroupNames'
        }
        @{
            Name = 'Public Network Access'
            Expression = 'if ($data.publicNetworkAccess)       { $data.publicNetworkAccess }       else { ''N/A'' }'
        }
        @{
            Name = 'Private Endpoints'
            Expression = '$peCount'
        }
        @{
            Name = 'Provisioning State'
            Expression = 'if ($data.provisioningState)         { $data.provisioningState }         else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'AVD Workspaces'
        TableNamePrefix = 'AVDWorkspacesTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Name'
            'Location'
            'Friendly Name'
            'Description'
            'Application Groups Count'
            'Application Groups'
            'Public Network Access'
            'Private Endpoints'
            'Provisioning State'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/Compute/AVDWorkspaces.ps1'
}

