#
# GENERATED by scripts/Build-ScoutServiceCollector.ps1 from manifests/specs/service-collectors.psd1 (AB#6741).
# Authored as data -- there is no source collector script to drift from. Edit the spec and
# regenerate; do not hand-patch this file.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/StorageBlobContainers'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $data = $1.PROPERTIES
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $ContainerName = if([string]::IsNullOrEmpty($1.name)){$null}else{(([string]$1.name) -split '/')[-1]}
                $PublicAccess = if([string]::IsNullOrEmpty($data.publicAccess)){'None'}else{[string]$data.publicAccess}
                $AnonymousAccess = if($PublicAccess -eq 'Container'){'YES - full anonymous read of blobs AND container listing'}elseif($PublicAccess -eq 'Blob'){'YES - anonymous read of blobs'}else{'No'}
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Storage Account'
            Expression = '$1.PARENTNAME'
        }
        @{
            Name = 'Container'
            Expression = '$ContainerName'
        }
        @{
            Name = 'Public Access'
            Expression = '$PublicAccess'
        }
        @{
            Name = 'Anonymous Access'
            Expression = '$AnonymousAccess'
        }
        @{
            Name = 'Lease State'
            Expression = '$data.leaseState'
        }
        @{
            Name = 'Lease Status'
            Expression = '$data.leaseStatus'
        }
        @{
            Name = 'Immutability Policy'
            Expression = '[string]$data.hasImmutabilityPolicy'
        }
        @{
            Name = 'Legal Hold'
            Expression = '[string]$data.hasLegalHold'
        }
        @{
            Name = 'Version Level WORM'
            Expression = '[string]$data.isVersionLevelWormEnabled'
        }
        @{
            Name = 'Last Modified'
            Expression = '[string]$data.lastModifiedTime'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
    )

    Export = @{
        WorksheetName = 'Blob Containers'
        TableNamePrefix = 'BlobContainersTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Storage Account'
            'Container'
            'Public Access'
            'Anonymous Access'
            'Lease State'
            'Lease Status'
            'Immutability Policy'
            'Legal Hold'
            'Version Level WORM'
            'Last Modified'
            'Resource U'
        )
        TagColumns = @()
        NumberFormat = '0'
        ConditionalText = @()
    }
}
