#
# GENERATED by scripts/Build-ScoutServiceCollector.ps1 from manifests/specs/service-collectors.psd1 (AB#6741).
# Authored as data -- there is no source collector script to drift from. Edit the spec and
# regenerate; do not hand-patch this file.
#
@{
    ResourceTypes = @(
        'AZSC/ARMChild/StorageLifecyclePolicies'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
                $data = $1.PROPERTIES
                $sub1 = $SUB | Where-Object { $_.id -eq $1.subscriptionId }
                $LifecycleRules = @($data.policy.rules)
                $RuleCount = $LifecycleRules.Count
                $EnabledRules = @($LifecycleRules | Where-Object { $_.enabled -ne $false }).Count
                $RuleNames = [string](@($LifecycleRules | ForEach-Object { $_.name }) -join ', ')
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Storage Account'
            Expression = '$1.PARENTNAME'
        }
        @{
            Name = 'Rule Count'
            Expression = '[string]$RuleCount'
        }
        @{
            Name = 'Enabled Rules'
            Expression = '[string]$EnabledRules'
        }
        @{
            Name = 'Rule Names'
            Expression = '$RuleNames'
        }
        @{
            Name = 'Last Modified'
            Expression = '[string]$data.lastModifiedTime'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
    )

    Export = @{
        WorksheetName = 'Storage Lifecycle Policies'
        TableNamePrefix = 'LifecyclePoliciesTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Storage Account'
            'Rule Count'
            'Enabled Rules'
            'Rule Names'
            'Last Modified'
            'Resource U'
        )
        TagColumns = @()
        NumberFormat = '0'
        ConditionalText = @()
    }
}
