#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Identity/SecurityPolicies.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'entra/securitypolicies'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
            $data = $1.properties

            # Default user role permissions
            $allowCreateApps = ''
            $allowCreateGroups = ''
            $allowReadOtherUsers = ''
            if ($data.defaultUserRolePermissions) {
                $allowCreateApps = [string]$data.defaultUserRolePermissions.allowedToCreateApps
                $allowCreateGroups = [string]$data.defaultUserRolePermissions.allowedToCreateSecurityGroups
                $allowReadOtherUsers = [string]$data.defaultUserRolePermissions.allowedToReadOtherUsers
            }
'@

    AdditionalRowLoops = @()

    TagLoop = $null

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Tenant ID'
            Expression = '$1.tenantId'
        }
        @{
            Name = 'Display Name'
            Expression = '$1.name'
        }
        @{
            Name = 'Guest User Role ID'
            Expression = '$data.guestUserRoleId'
        }
        @{
            Name = 'Allow Invites From'
            Expression = '$data.allowInvitesFrom'
        }
        @{
            Name = 'Allow Email Subscriptions'
            Expression = '[string]$data.allowedToSignUpEmailBasedSubscriptions'
        }
        @{
            Name = 'Allow Email Verified Join'
            Expression = '[string]$data.allowEmailVerifiedUsersToJoinOrganization'
        }
        @{
            Name = 'Allow SSPR'
            Expression = '[string]$data.allowedToUseSSPR'
        }
        @{
            Name = 'Block MSOL PowerShell'
            Expression = '[string]$data.blockMsolPowerShell'
        }
        @{
            Name = 'Allow Create Apps'
            Expression = '$allowCreateApps'
        }
        @{
            Name = 'Allow Create Security Groups'
            Expression = '$allowCreateGroups'
        }
        @{
            Name = 'Allow Read Other Users'
            Expression = '$allowReadOtherUsers'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
    )

    Export = @{
        WorksheetName = 'Security Policies'
        TableNamePrefix = 'SecPolTable_'
        Columns = @(
            'Display Name'
            'Guest User Role ID'
            'Allow Invites From'
            'Allow Email Subscriptions'
            'Allow Email Verified Join'
            'Allow SSPR'
            'Block MSOL PowerShell'
            'Allow Create Apps'
            'Allow Create Security Groups'
            'Allow Read Other Users'
            'Resource U'
        )
        TagColumns = @()
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/Identity/SecurityPolicies.ps1'
}

