#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Hybrid/ArcDataControllers.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.azurearcdata/datacontrollers'
    )

    ResourceTypeMatching = 'Grouped'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
            $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
            $data = $1.PROPERTIES
            $Tags = if (![string]::IsNullOrEmpty($1.tags.psobject.properties)) { $1.tags.psobject.properties } else { '0' }

            $k8sResourceId     = if ($data.k8sRaw.metadata.namespace) { $data.k8sRaw.metadata.namespace } else { 'N/A' }
            $laWorkspaceId     = if ($data.logAnalyticsWorkspaceConfig.workspaceId) { $data.logAnalyticsWorkspaceConfig.workspaceId } else { 'N/A' }
            $metricsUploadState = if ($data.uploadStatus.metrics.lastUploadedAt) { $data.uploadStatus.metrics.lastUploadedAt } else { 'N/A' }
            $logsUploadState    = if ($data.uploadStatus.logs.lastUploadedAt)    { $data.uploadStatus.logs.lastUploadedAt }    else { 'N/A' }
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Connectivity Mode'
            Expression = 'if ($data.infrastructure)         { $data.infrastructure }         else { ''N/A'' }'
        }
        @{
            Name = 'K8s Namespace'
            Expression = '$k8sResourceId'
        }
        @{
            Name = 'Log Analytics Workspace'
            Expression = '$laWorkspaceId'
        }
        @{
            Name = 'Metrics Last Uploaded'
            Expression = '$metricsUploadState'
        }
        @{
            Name = 'Logs Last Uploaded'
            Expression = '$logsUploadState'
        }
        @{
            Name = 'Provisioning State'
            Expression = 'if ($data.provisioningState)      { $data.provisioningState }      else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Arc Data Controllers'
        TableNamePrefix = 'ArcDataCtrlTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Name'
            'Location'
            'Connectivity Mode'
            'K8s Namespace'
            'Log Analytics Workspace'
            'Metrics Last Uploaded'
            'Logs Last Uploaded'
            'Provisioning State'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/Hybrid/ArcDataControllers.ps1'
}

