#
# GENERATED by scripts/ConvertTo-ScoutCollectorDefinition.ps1 from Modules/Public/InventoryModules/Hybrid/ArcSites.ps1 (AB#5660).
# Field expressions are copied verbatim from the original collector and evaluate in an
# equivalent scope -- see docs/design/decisions/declarative-collectors.md.
# Review before trusting; regenerate rather than hand-patch if the source collector changes.
#
@{
    ResourceTypes = @(
        'microsoft.azurestackhci/sites'
        'microsoft.edgeconfig/sites'
        'microsoft.hybridcompute/sites'
    )

    ResourceTypeMatching = 'SinglePass'

    AdditionalFilter = $null

    FilterPreamble = ''

    RowLoopVariable = '1'

    Preamble = @'
$ResUCount = 1
            $sub1 = $SUB | Where-Object { $_.Id -eq $1.subscriptionId }
            $data = $1.PROPERTIES
            $Tags = if (![string]::IsNullOrEmpty($1.tags.psobject.properties)) { $1.tags.psobject.properties } else { '0' }

            # Determine site type from resource type
            $siteType = switch ($1.TYPE) {
                'microsoft.azurestackhci/sites'    { 'Azure Local (HCI)' }
                'microsoft.edgeconfig/sites'       { 'Edge Config' }
                'microsoft.hybridcompute/sites'    { 'Arc Hybrid Compute' }
                default { 'Unknown' }
            }
'@

    AdditionalRowLoops = @()

    TagLoop = @{
        Variable = 'Tag'
        Source = '$Tags'
        Preamble = ''
    }

    Fields = @(
        @{
            Name = 'ID'
            Expression = '$1.id'
        }
        @{
            Name = 'Subscription'
            Expression = '$sub1.Name'
        }
        @{
            Name = 'Resource Group'
            Expression = '$1.RESOURCEGROUP'
        }
        @{
            Name = 'Name'
            Expression = '$1.NAME'
        }
        @{
            Name = 'Location'
            Expression = '$1.LOCATION'
        }
        @{
            Name = 'Site Type'
            Expression = '$siteType'
        }
        @{
            Name = 'Display Name'
            Expression = 'if ($data.displayName)             { $data.displayName }             else { ''N/A'' }'
        }
        @{
            Name = 'Address'
            Expression = 'if ($data.address)                 { $data.address }                 else { ''N/A'' }'
        }
        @{
            Name = 'Country/Region'
            Expression = 'if ($data.country)                 { $data.country }                 else { ''N/A'' }'
        }
        @{
            Name = 'Description'
            Expression = 'if ($data.description)             { $data.description }             else { ''N/A'' }'
        }
        @{
            Name = 'Provisioning State'
            Expression = 'if ($data.provisioningState)       { $data.provisioningState }       else { ''N/A'' }'
        }
        @{
            Name = 'Resource U'
            Expression = '$ResUCount'
        }
        @{
            Name = 'Tag Name'
            Expression = '[string]$Tag.Name'
        }
        @{
            Name = 'Tag Value'
            Expression = '[string]$Tag.Value'
        }
    )

    Export = @{
        WorksheetName = 'Arc Sites'
        TableNamePrefix = 'ArcSitesTable_'
        Columns = @(
            'Subscription'
            'Resource Group'
            'Name'
            'Location'
            'Site Type'
            'Display Name'
            'Address'
            'Country/Region'
            'Description'
            'Provisioning State'
            'Resource U'
        )
        TagColumns = @(
            'Tag Name'
            'Tag Value'
        )
        TagColumnsBefore = $null
        NumberFormat = '0'
        ConditionalText = @()
    }

    SourceCollector = 'Modules/Public/InventoryModules/Hybrid/ArcSites.ps1'
}

